### ISSUE TITLE
Desktop Notifications not working on Arch Linux

### ISSUE THREAD

**Issue by GrimPixel** [vjousse/pomodorolm#29] opened 2024-05-17 06:28 UTC
They just don't pop up.

**Comment by vjousse** [comment] 2024-05-17 06:46
I'm currently using Archlinux and the notifications are working fine for me. Could you give a little bit more details about your setup?

**Comment by GrimPixel** [comment] 2024-05-17 07:04
Glad to know it. That's MATE.

**Comment by vjousse** [comment] 2024-05-17 07:38
Thanks, I'll try locally. I suppose that other notifications are working fine? Could you give me an example of an app you are using under MATE where the notifications are working fine?

**Comment by GrimPixel** [comment] 2024-05-17 08:03
I got this one https://github.com/coolcode/tomato-clock-rs

**Comment by vjousse** [comment] 2024-05-20 17:12
Thanks, could you try the following command and tell me if it's working as expected? 
`notify-send test test`

Do you start mate with `startx` or with a Login Manager (and which one?)

**Comment by vjousse** [comment] 2024-05-21 10:25
It seems that I can't reproduce your problem. I got notifications under Mate using both tomato-clock or pomodorolm, see the screenshots above. For pomodrolm, the notification is triggered only when moving to the next round FYI.

I'm using the daemon `mate-notification-daemon` for notifications.

Could you provide the output of `cat ~/.config/pomodorolm/config.toml`?

![tomato-clock](https://github.com/vjousse/pomodorolm/assets/154904/249d867b-dbcb-4af5-9592-41aa78845aae)

![pomodorolm-notification-mate](https://github.com/vjousse/pomodorolm/assets/154904/e5786cd9-9baa-41cd-8005-af25febec9fb)

**Comment by GrimPixel** [comment] 2024-05-21 13:10
I clicked on the forward icon and the notification is shown. When it's time up normally, there is no notification.

```
always_on_top = true
auto_start_work_timer = true
auto_start_break_timer = true
desktop_notifications = true
long_break_duration = 1200
max_round_number = 4
minimize_to_tray = true
minimize_to_tray_on_close = true
pomodoro_duration = 60
short_break_duration = 300
tick_sounds_during_work = true
tick_sounds_during_break = true
```

**Closed** 2024-05-21 15:31 UTC
Labels: bug

**Comment by vjousse** [comment] 2024-05-21 16:31
I've pushed the 0.0.5 release to aur, the problem should now be solved. Thanks for the report!
